name: CICD Pwskills calculator

on:
  push:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Installing Dependencies
        run: |
            pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
           python -m pytest

      - name: create build Artifact
        run: |
          mkdir build
          cp -r App build/
          zip -r python-app-build.zip build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app-build
          path: python-app-build.zip

  deploy:
      needs: build-test
      runs-on: ubuntu-latest

      steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app-build

      - name: Simulate Deployment
        run: |
          unzip python-app-build.zip
          ls -R

    
